version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: meu-app-mongodb-container
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
      - ./mongodb-init.js:/docker-entrypoint-initdb.d/mongodb-init.js
